"""Sandboxed Python execution — shared by the GRPO reward and the ReAct agent.

SECURITY: this runs model-generated code. It is safe to run inside an isolated
container (Kaggle kernels, Docker, a throwaway VM) — which is exactly where
training happens. Do NOT point this at a machine with data you care about.
Mitigations here: separate subprocess, hard wall-clock timeout, a fresh temp
dir as CWD, and (on POSIX) CPU/address-space rlimits. It is a sandbox by
convention, not a hardened jail.
"""

from __future__ import annotations

import os
import re
import secrets
import subprocess
import sys
import tempfile
import textwrap

_CODE_BLOCK = re.compile(r"```(?:python)?\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)


def extract_code(text: str) -> str:
    """Pull the last ```python block; fall back to text after </think>."""
    blocks = _CODE_BLOCK.findall(text or "")
    if blocks:
        return blocks[-1].strip()
    if "</think>" in text:
        return text.split("</think>", 1)[1].strip()
    return (text or "").strip()


# POSIX-only resource limiting; a no-op on Windows.
_PREAMBLE = textwrap.dedent("""
    import resource, sys
    try:
        resource.setrlimit(resource.RLIMIT_CPU, (10, 10))
        resource.setrlimit(resource.RLIMIT_AS, (2 * 1024**3, 2 * 1024**3))
    except Exception:
        pass
""") if os.name == "posix" else ""

# Runner injected ahead of every per-test harness for score_solution(). It
# reads the nonce + result-file path from argv, immediately scrubs argv so
# the candidate code (exec'd into its own throwaway namespace, `_ns`) can't
# just read them back out, and only writes the nonce to disk if the candidate
# code + setup + test string executes start-to-finish without raising. There
# is no stdout involved anywhere in this decision.
_NONCE_RUNNER = textwrap.dedent("""
    import sys as _sys

    def _run_one():
        _nonce = _sys.argv[1]
        _result_path = _sys.argv[2]
        _sys.argv = _sys.argv[:1]  # scrub before candidate code ever runs
        _ns = {}
        try:
            exec(_candidate_src, _ns)
        except Exception:
            return
        with open(_result_path, "w", encoding="utf-8") as _f:
            _f.write(_nonce)

""")


def _run(script: str, timeout: float):
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "prog.py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(script)
        try:
            p = subprocess.run(
                [sys.executable, "-I", path],
                cwd=tmp, capture_output=True, text=True, timeout=timeout,
            )
            return p.returncode, p.stdout, p.stderr
        except subprocess.TimeoutExpired:
            return -1, "", "TIMEOUT"
        except Exception as e:  # pragma: no cover
            return -1, "", f"EXEC_ERROR: {e}"


def run_code(code: str, timeout: float = 10.0):
    """Execute code as-is. Returns (ok, stdout, stderr)."""
    rc, out, err = _run(_PREAMBLE + code, timeout)
    return rc == 0, out, err


def score_solution(code: str, tests: list[str], setup: str = "",
                   timeout: float = 12.0) -> float:
    """Fraction of unit tests the candidate code passes (0.0-1.0).

    Each test runs in its own subprocess (so one test can't sabotage or leak
    state into the next), and pass/fail is decided over a channel the
    candidate cannot control. A per-run cryptographically random NONCE
    (secrets.token_hex) is generated by the parent; the harness writes it to
    a parent-chosen result file ONLY after `code + setup + test` executes
    without raising. The parent then checks the file's contents against the
    nonce it generated. A candidate that does `print("SCORE=1/1")`, calls
    `sys.exit(0)` early, or swallows the assertion's exception gains
    nothing: the nonce never appears in stdout, in the script text, or
    anywhere else the candidate could discover it in advance, and if the
    assert doesn't genuinely pass, the write is simply never reached.

    A candidate that doesn't even import/define cleanly scores 0.

    Residual limitations (this is a sandbox by convention, not a hardened
    jail -- run it only inside a disposable container, e.g. a Kaggle kernel,
    Docker, or a throwaway VM): candidate code still executes in the *same
    interpreter process* as the harness, isolated only by a fresh exec()
    namespace, not a real process boundary. A sufficiently adversarial
    candidate could in principle still recover the nonce via CPython frame
    introspection (walking `sys._getframe().f_back`) or, on Linux, by
    reading `/proc/self/cmdline` before argv is scrubbed. Neither is
    defended against here; both require a real sandbox/container boundary,
    not application-level tricks, to close for good.
    """
    if not tests:
        return 0.0
    passed = 0
    with tempfile.TemporaryDirectory() as tmp:
        for i, t in enumerate(tests):
            nonce = secrets.token_hex(16)
            result_path = os.path.join(tmp, f"result_{i}.txt")
            prog_path = os.path.join(tmp, f"prog_{i}.py")
            combined = code + "\n" + (setup or "") + "\n" + t

            harness = _PREAMBLE + _NONCE_RUNNER
            harness += "_candidate_src = " + repr(combined) + "\n"
            harness += "_run_one()\n"
            with open(prog_path, "w", encoding="utf-8") as f:
                f.write(harness)

            try:
                subprocess.run(
                    [sys.executable, "-I", prog_path, nonce, result_path],
                    cwd=tmp, capture_output=True, text=True, timeout=timeout,
                )
            except Exception:
                continue  # timeout, crash, etc. -- no nonce, no credit

            if os.path.exists(result_path):
                try:
                    with open(result_path, "r", encoding="utf-8") as f:
                        if f.read() == nonce:
                            passed += 1
                except Exception:
                    pass
    return passed / len(tests)


if __name__ == "__main__":
    # Self-check: correct code scores 1.0, wrong code scores 0.0, and a
    # forged-stdout / early-exit attempt still scores 0.0 -- proving the
    # reward no longer depends on anything the candidate can print or exit.
    good = "def add(a, b):\n    return a + b\n"
    bad = "def add(a, b):\n    return a - b\n"
    forged = (
        "print('SCORE=1/1')\n"
        "import sys\n"
        "sys.exit(0)\n"
        "def add(a, b):\n"
        "    return a - b\n"
    )
    tests = ["assert add(2, 3) == 5"]

    s_good = score_solution(good, tests)
    s_bad = score_solution(bad, tests)
    s_forged = score_solution(forged, tests)

    print(f"correct code:        {s_good}")
    print(f"wrong code:          {s_bad}")
    print(f"forged stdout+exit:  {s_forged}")

    assert s_good == 1.0, "correct code should score 1.0"
    assert s_bad == 0.0, "wrong code should score 0.0"
    assert s_forged == 0.0, "forged SCORE=/early-exit attempt should score 0.0"
    print("OK: reward channel is not controllable via stdout or early exit.")
